In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        pass
        #print(os.path.join(dirname, filename))


# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
from sklearn.compose import ColumnTransformer, make_column_transformer
from sklearn.preprocessing import OneHotEncoder

data=[]

i = 0  

files = str(i) + '.dat'
chemin = '/kaggle/input/supernova/supernovae_data'
chemin_fichier = os.path.join(chemin, files)

df = pd.read_csv(chemin_fichier, delimiter=' ')    #read every dat file and the delimiter is space so it can generate a dataframe object 
print("----------------------------------------------------------------------------------------------------------------")

print(df.head())
print(df.shape)

print("----------------------------------------------------------------------------------------------------------------")

matrix = df.values  #converts the dataframe into a an array type and the datatype inside the array is object and it drops the first line

print(matrix) 
print(matrix.shape)

#we will do the onehotencoding on the second column, we do it to the df

df = pd.DataFrame(matrix)  #this will revert back the array into dataframe 

print("----------------------------------------------------------------------------------------------------------------")
print(df)

print("----------------------------------------------------------------------------------------------------------------")

encoder = OneHotEncoder(sparse_output=False)  #this will enables as to have an output as dataframe 

ct = make_column_transformer(
  (encoder , [1]),
  remainder = 'drop'
)
ct.set_output(transform = 'pandas')
one_hot_encoded = ct.fit_transform(df)

ma = np.array(one_hot_encoded)  # convert it to an array

print(ma)
print(ma.shape)

print("----------------------------------------------------------------------------------------------------------------")

resultat = np.hstack((matrix[:, [0, 2, 3]], ma))

n = resultat.shape[0]
print(n ,'is the  number of lines of the first star')

lm = 161-n
padding = np.zeros((lm, 7)) #7 is the mjd, flux, flux_error, and 4  columns of the filter

print(padding)

print("----------------------------------------------------------------------------------------------------------------")

resultat = np.vstack((resultat, padding))
print(resultat)
print(resultat.shape)
data.append(resultat)

----------------------------------------------------------------------------------------------------------------
      mjd filter    flux  flux_error    zp zpsys
0   0.000   desg -4.3860       4.679  27.5    ab
1   0.011   desr -0.5441       2.751  27.5    ab
2   0.027   desi  0.4547       4.627  27.5    ab
3   0.043   desz -1.0470       4.462  27.5    ab
4  13.043   desg -4.2390       4.366  27.5    ab
(108, 6)
----------------------------------------------------------------------------------------------------------------
[[0.0 'desg' -4.386 4.679 27.5 'ab']
 [0.0110000000058789 'desr' -0.5441 2.751 27.5 'ab']
 [0.0270000000018626 'desi' 0.4547 4.627 27.5 'ab']
 [0.0430000000051222 'desz' -1.047 4.462 27.5 'ab']
 [13.043000000005122 'desg' -4.239 4.366 27.5 'ab']
 [13.05000000000291 'desr' 4.695 3.46 27.5 'ab']
 [13.05800000000454 'desi' 6.291 6.248 27.5 'ab']
 [13.074000000000524 'desz' 6.412 5.953 27.5 'ab']
 [21.05000000000291 'desg' 1.588 2.681 27.5 'ab']
 [21.05800000000454 'desr

In [3]:
from sklearn.compose import ColumnTransformer, make_column_transformer
from sklearn.preprocessing import OneHotEncoder

data=[]

for i in range (2000):
    
    files = str(i) + '.dat'
    chemin = '/kaggle/input/supernova/supernovae_data'
    chemin_fichier = os.path.join(chemin, files)
    df = pd.read_csv(chemin_fichier, delimiter = ' ')   
    matrix = df.values 
    df = pd.DataFrame(matrix)  
    
    encoder = OneHotEncoder(sparse_output = False)  
    
    ct = make_column_transformer(
      (encoder , [1]),
      remainder = 'drop'
    )
    ct.set_output(transform = 'pandas')
    one_hot_encoded = ct.fit_transform(df)
    
    ma = np.array(one_hot_encoded)
    
    resultat = np.hstack((matrix[:, [0, 2, 3]], ma))
    
    n = resultat.shape[0]
    lm = 161-n
    padding = np.zeros((lm, 7))
    
    resultat = np.vstack((resultat, padding))
    data.append(resultat)
    

In [4]:
chemin = '/kaggle/input/supernove-classification'
fichier = 'salt2_feature.csv'
chemin_fichier = os.path.join(chemin, fichier)

df = pd.read_csv(chemin_fichier , delimiter = ';')

matrix = df.values   #this will transforme the dataframe into numpy arrays 

df = pd.DataFrame(matrix)
print(df)

print("----------------------------------------------------------------------------------------------------------------")

encoder = OneHotEncoder(sparse_output = False)
print(df[6])
print("----------------------------------------------------------------------------------------------------------------")

ct = make_column_transformer(
    (encoder , [6]),
    remainder = 'drop'
)

ct.set_output(transform = 'pandas')

y = ct.fit_transform(df)

print(y.shape)
print(y)

           0         1          2         3         4         5    6
0        0.0  0.664885  64.334480  0.000003  2.734004 -0.218864  2.0
1        1.0  0.732481  -3.667963  0.000003  0.637645 -0.016488  3.0
2        2.0  1.054637 -60.927470  0.000018  0.014775 -0.397927  2.0
3        3.0  1.160663 -63.861990  0.000011 -3.000000 -0.036135  2.0
4        4.0  0.211863  58.629560  0.000012  3.000000  0.127932  2.0
...      ...       ...        ...       ...       ...       ...  ...
1995  1995.0  0.177504 -80.734400  0.000013 -1.557493 -0.008078  2.0
1996  1996.0  0.564805  62.196930  0.000002 -2.685392  0.268322  3.0
1997  1997.0  0.436681  18.547850  0.000007  3.000000  0.396048  2.0
1998  1998.0  0.452387  63.681560  0.000003  3.000000 -0.077521  2.0
1999  1999.0  0.552008  56.722690  0.000003 -2.201142  0.137391  1.0

[2000 rows x 7 columns]
----------------------------------------------------------------------------------------------------------------
0       2.0
1       3.0
2       2.

In [5]:
from sklearn.model_selection import train_test_split

data = np.array(data, dtype = np.float32)
print(data.shape)

X_train, X_test,y_train, y_test = train_test_split(data, y, random_state = 104, test_size=0.2, shuffle=True)

print(f"Training files: {len(X_train)}, label files: {len(y_train)}")
print(y_train.shape)

(2000, 161, 7)
Training files: 1600, label files: 1600
(1600, 3)


In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization, Reshape
from tensorflow.keras.utils import to_categorical
import tensorflow as tf

model = Sequential([
  Reshape((161, 7, 1), input_shape=(161, 7)),   #this reshapes the input to (161,7,1) before feeding it to the neural network
  BatchNormalization(),
  Conv2D(64, (3, 3), activation='relu', padding='same'), #means the ouput size is the same as the input size meaning padding zeros around the edges are needed
  BatchNormalization(),
  MaxPooling2D(pool_size=(2, 1)), #the window size is 2 by 1 and the stride is by default 1 meaning the height is reduced by 2
  Conv2D(32, (3, 3), activation='relu', padding='same'),
  BatchNormalization(),
  MaxPooling2D(pool_size=(2, 1)),
  Conv2D(16, (3, 3), activation='relu', padding='same'),
  BatchNormalization(),
  MaxPooling2D(pool_size=(2, 1)),
  Flatten(),
  Dense(256, activation='relu'),
  BatchNormalization(),
  Dropout(0.1),    #10% of the neurons are dropped randomly
  Dense(128, activation='relu'),
  BatchNormalization(),
  Dropout(0.1),
  Dense(64, activation='relu'),
  Dropout(0.1),
  Dense(3, activation='softmax')
  ])
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

from keras.callbacks import EarlyStopping

# Define EarlyStopping callback
early_stop = EarlyStopping(
    monitor='val_accuracy',     # Watch validation accuracy
    patience=5,             # Number of epochs to wait before stopping
    restore_best_weights=True  # Revert to best weights after stopping
)


model.fit(
    X_train, y_train,
    epochs=50,   #number if passes through the whole dataset
    validation_split=0.1, #reserves 10% of your training data to validation
    callbacks=[early_stop],
    batch_size=10
)


2025-10-01 21:45:25.642387: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1759355125.917648      13 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1759355126.002289      13 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/reshape.py:39: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
2025-10-01 21:45:43.000755: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Fai

Epoch 1/50
144/144 ━━━━━━━━━━━━━━━━━━━━ 15s 45ms/step - accuracy: 0.5095 - loss: 1.1177 - val_accuracy: 0.6562 - val_loss: 1.5165
Epoch 2/50
144/144 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.6656 - loss: 0.7701 - val_accuracy: 0.6562 - val_loss: 2.1539
Epoch 3/50
144/144 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.6904 - loss: 0.6985 - val_accuracy: 0.6625 - val_loss: 1.5001
Epoch 4/50
144/144 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.7566 - loss: 0.6296 - val_accuracy: 0.6750 - val_loss: 0.9918
Epoch 5/50
144/144 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.7441 - loss: 0.5890 - val_accuracy: 0.6938 - val_loss: 0.8237
Epoch 6/50
144/144 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.7651 - loss: 0.5736 - val_accuracy: 0.6687 - val_loss: 1.3525
Epoch 7/50
144/144 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.7638 - loss: 0.5566 - val_accuracy: 0.6500 - val_loss: 1.5919
Epoch 8/50
144/144 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.7447 - loss: 0.5844 - val_acc

In [7]:
print(X_test.shape)
print(y_test.shape)

test_loss, test_acc = model.evaluate(X_test, y_test) #test_loss = categorical cross entropy loss, test_acc = the accuracy of the model on test data.

print(f"\nTest accuracy: {test_acc:.4f}")

y_pred_probs = model.predict(X_test)

from sklearn.metrics import roc_auc_score #ROC-AUC (Receiver Operating Characteristic – Area Under Curve)

auc = roc_auc_score(y_test, y_pred_probs)
print("AUC Score:", auc)

(400, 161, 7)
(400, 3)
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7993 - loss: 0.7390

Test accuracy: 0.7875
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step
AUC Score: 0.8605886242941794


In [8]:
y_pred=model.predict(X_test)
y_pred=np.argmax(y_pred, axis=1)
y_test=np.argmax(y_test, axis=1)
from sklearn.metrics import confusion_matrix,classification_report
print(classification_report(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print(cm)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
              precision    recall  f1-score   support

           0       0.72      0.64      0.67        96
           1       0.81      0.97      0.88       260
           2       0.50      0.07      0.12        44

    accuracy                           0.79       400
   macro avg       0.68      0.56      0.56       400
weighted avg       0.76      0.79      0.75       400

[[ 61  34   1]
 [  7 251   2]
 [ 17  24   3]]
